create table Plantings(
plantingId integer not null primary key autoincrement,
packetId references SeedPackets(packetId),
plantingCode text,
datePlanted integer,
dateGerminated integer,
numberPlanted integer,
numberGerminated integer,
areaPlanted text,
plantingNote text,
germinationNote text,
generalNote
);

insert into Plantings(
packetId, 
plantingCode,
datePlanted,
dateGerminated,
numberPlanted,
numberGerminated,
areaPlanted,
plantingNote,
germinationNote,
generalNote) values 
(1,
'trees1',
0,
1,
4,
4,
'Front of house',
'trees were mulched',
'leaves appeared in spring',
'flowered and beared fruit after 2 years'),
(3,
'trees2',
0,
1,
4,
3,
'Hill accross creek',
'trees were mulched',
'leaves appeared in spring on three trees only',
'not flowered yet');